trigger:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: cet-iac

variables: 
- group: kopps-public
- group: spoke00-general-params
- name: imageRepository
  value: $(appName)
- name: githubPath
  value: $(Agent.BuildDirectory)/github
- name: dockerfilePath
  value: '$(Agent.BuildDirectory)/github/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: image
  value: '$(imageRepository):$(tag)'
- name: dockerImage
  value: '$(image)'
- name: isApi
  value: false

pool:  
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  
  jobs:
  - template: templates/deploy-docker-image.yml@cet-iac

          
