trigger:
  branches:
    include:
    - main

variables:
- group: spoke00-ref-general-params
- name: appName
  value: kopps-public-ref
- name: parametersFileName
  value: kopps-public.ref.parameters.json
- name: imageRepository
  value: kopps-public
- name: dockerfilePath
  value: '$(Pipeline.Workspace)/github/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: image
  value: '$(imageRepository):$(tag)'
- name: isApi
  value: false


resources:
  repositories:
   - repository: cet-iac
     type: git
     name: cet-iac

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Test
  displayName: Test

  jobs:
    - job: InstallNpm
      displayName: Install NPM packages
      steps:
      - template: templates/npm-test.yml@cet-iac
        parameters:
          command: 'ci --development'
          workingDir: ''
    
    - job: TestNPM
      displayName: Test NPM package
      steps:
      - template: templates/npm-test.yml@cet-iac
        parameters:
          command: 'run test'
          workingDir: ''
        
    - template: templates/docker-test.yml@cet-iac
      parameters:
        dockerComposeFile: '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'

- stage: Build
  displayName: Build and push to ref

  jobs:
  - template: templates/deploy-docker-image.yml@cet-iac