trigger:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: cet-iac

variables: 
- group: kopps-public
- group: spoke00-general-params
- name: imageRepository
  value: $(appName)
- name: dockerfilePath
  value: '$(Agent.BuildDirectory)/build/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: image
  value: '$(imageRepository):$(tag)'
- name: dockerImage
  value: '$(image)'
- name: isApi
  value: false

pool:  
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: CreateInfrastructure
    displayName: Create infrastructure
    steps:
    - template: templates/deploy-infra.yml@cet-iac
      parameters:
        appname: $(appName)
        azureServiceConnection: $(azureSubscription)

  - job: Build
    displayName: Build image for $(appName)
    dependsOn: CreateInfrastructure
    steps:
      - checkout: self
        path: build

      - task: Docker@2
        inputs:
          containerRegistry: 'kthregistryacr'
          command: 'login'
      
      - task: Docker@2
        inputs:
          containerRegistry: '$(containerRegistry)'
          command: 'login'
      - task: Docker@2
        displayName: Build and push an image to container registry
        inputs:
          command: buildAndPush
          repository: $(imageRepository)
          dockerfile: $(dockerfilePath)
          containerRegistry: $(dockerRegistryServiceConnection)
          tags: |
            $(tag)

      - task: AzureWebAppContainer@1
        displayName: 'Deploy $(image) to Azure'
        inputs:
          azureSubscription: $(azureSubscription)
          appName: $(appName)
          imageName: $(containerRegistry).azurecr.io/$(image)

          
