pr: none
trigger:
  branches:
    include:
    - master

variables:
- group: studadm-general-params
- group: studadm-spoke1-ref
- name: appName
  value: kopps-public-react-web-ref
- name: parametersFileName
  value: kopps-public.ref.parameters.json
- name: imageRepository
  value: kopps-public-react-web
- name: dockerfilePath
  value: '$(Pipeline.Workspace)/github/Dockerfile'
- name: tag
  value: '$(Build.BuildId)'
- name: image
  value: '$(imageRepository):$(tag)'
- name: isApi
  value: false


resources:
  repositories:
  - repository: cet-iac
    type: git
    name: Cloud Excellence Team/cet-iac
    ref: main

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: Test
  displayName: Unit and integration testing
  jobs:
    - template: templates/docker-test.yml@cet-iac
      parameters:
        jobName: DockerUnitTest
        displayName: Docker compose unit test
        dockerComposeFilePath: '$(Pipeline.Workspace)/github/docker-compose-unit-tests.yml'

    - template: templates/docker-test.yml@cet-iac
      parameters:
        jobName: DockerIntegrationTest
        displayName: Docker compose integration test
        dockerComposeFilePath: '$(Pipeline.Workspace)/github/docker-compose-integration-tests.yml'


- stage: Build
  displayName: Build and push to ref
  jobs:
    - template: templates/deploy-docker-image.yml@cet-iac