trigger: none

parameters:
  - name: generalParams
    type: string
    displayName: General params name (from library, <team-name>-<env>-general-params)
  - name: appName
    type: string
    displayName: App name (<app-name>-<env>)
  - name: parametersFileName
    type: string
    displayName: Parameters filename (from .azure folder, <app-name>.<env>.parameters.json)
  - name: imageRepository
    type: string
    displayName: Image repo for this app (<app-name>, should be same for both envs)
  - name: isApi
    type: boolean
    displayName: Is this an API?
    default: false
  - name: deploySlot
    type: boolean
    displayName: Deploy a pre-production slot for this application?
    default: true

variables:
  - group: ${{ parameters.generalParams }}
  - name: appName
    value: ${{ parameters.appName }}
  - name: parametersFileName
    value: ${{ parameters.parametersFileName }}
  - name: imageRepository
    value: ${{ parameters.imageRepository }}
  - name: isApi
    value: ${{ parameters.isApi }}
  - name: deploySlot
    value: ${{ parameters.deploySlot }}

resources:
  repositories:
    - repository: cet-iac
      type: git
      name: cet-iac

pool:
  vmImage: 'ubuntu-latest'

stages:
  - template: templates/deploy-infra.yml@cet-iac
